TabRepository/Models/Friend.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TabRepository.Models
{
    public class Friend
    {
        [Key, ForeignKey("User1")]
        public string User1Id { get; set; }

        [Key, ForeignKey("User2")]
        public string User2Id { get; set; }

        public FriendStatus Status { get; set; }

        public string ActingUserId { get; set; }

        public virtual ApplicationUser User1 { get; set; }

        public virtual ApplicationUser User2 { get; set; }

        public virtual ApplicationUser ActingUser { get; set; }
    }

    public enum FriendStatus
    {
        None,
        Friends,
        Blocked,
        Requested
    }

    public enum Direction
    {
        From,
        To
    }
}

TabRepository/ViewModels/FriendViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TabRepository.Models;

namespace TabRepository.ViewModels
{
    public class FriendViewModel
    {
        public string FromUsername { get; set; }

        public string ToUsername { get; set; }

        public string Username { get; set; }

        public FriendStatus Status { get; set; }

        public Direction Direction { get; set; }

        public bool IsCurrentUser { get; set; }

        public string ImageFilePath { get; set; }
    }
}

TabRepository/Controllers/FriendsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using TabRepository.Data;
using TabRepository.Models;
using TabRepository.ViewModels;

namespace TabRepository.Controllers
{
    [Authorize]
    public class FriendsController : Controller
    {
        private ApplicationDbContext _context;

        public FriendsController(ApplicationDbContext context)
        {
            _context = context; 
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        // GET: Friends
        public ActionResult Index()
        {
            return View();
        }

        public ApplicationUser GetCurrentUser()
        {
            string currentUserId = User.GetUserId();

            return _context.Users.FirstOrDefault(u => u.Id == currentUserId);
        }

        [HttpPost]
        public ActionResult FuzzySearch(string searchString)
        {
            if (searchString == null)
            {
                return Json(new object());
            }

            searchString = searchString.Trim();
            List<object> usernames = new List<object>();

            var users = _context
                .Users
                .Where(u => u.UserName.StartsWith(searchString))
                .OrderBy(u => u.UserName)
                .Take(10);

            foreach (ApplicationUser user in users)
            {
                usernames.Add(new { username = user.UserName });
            }

            return Json(usernames);
        }

        [HttpGet]
        public ActionResult Search(string searchString, bool exact = false)
        {
            if (searchString == null)
            {
                return View(new List<FriendViewModel>());
            }

            searchString = searchString.Trim();
            string currentUserId = User.GetUserId();

            // Require at least 3 characters (arbitrarily chose 3) for wildcard username matching to 
            // prevent users from accessing large subsets of user list via search (i.e. searching "a")
            var users = (exact == true || searchString.Length < 3)
                        ?
                        from u in _context.Users
                        from f in _context.Friends.Where(f => (u.Id == f.User1Id && currentUserId == f.User2Id) || (u.Id == f.User2Id && currentUserId == f.User1Id)).DefaultIfEmpty()
                        where u.UserName.ToLower() == searchString.ToLower()
                        orderby u.UserName
                        select new { u.Id, u.UserName, u.ImageFilePath, f.ActingUserId, f.User1Id, f.User2Id, Status = f.Status == null ? FriendStatus.None : f.Status }
                        :
                        from u in _context.Users
                        from f in _context.Friends.Where(f => (u.Id == f.User1Id && currentUserId == f.User2Id) || (u.Id == f.User2Id && currentUserId == f.User1Id)).DefaultIfEmpty()
                        where u.UserName.StartsWith(searchString)
                        orderby u.UserName
                        select new { u.Id, u.UserName, u.ImageFilePath, f.ActingUserId, f.User1Id, f.User2Id, Status = f.Status == null ? FriendStatus.None : f.Status };

            List<FriendViewModel> viewModel = new List<FriendViewModel>();

            foreach (var user in users)
            {
                var vm = new FriendViewModel();

                vm.Username = user.UserName;
                vm.Status = user.Status;
                vm.ImageFilePath = user.ImageFilePath;
                
                if (user.User1Id != null && user.User2Id != null)
                {
                    if (user.ActingUserId == currentUserId)
                    {
                        vm.Direction = Direction.To;
                    }
                    else
                    {
                        vm.Direction = Direction.From;
                    }
                }

                if (user.Id == currentUserId)
                {
                    vm.IsCurrentUser = true;
                }
                else
                {
                    vm.IsCurrentUser = false;
                }

                viewModel.Add(vm);
            }

            return View(viewModel);
        }

        [HttpPost]
        public ActionResult AddFriend(string username)
        {
            var friendStatus = CheckFriendStatus(username);

            using (var transaction = _context.Database.BeginTransaction())
            {
                try
                {
                    if (friendStatus != FriendStatus.Blocked)
                    {
                        string currentUserId = User.GetUserId();
                        string currentUsername = User.GetUsername();
                        var otherUserInDb = _context.Users.Where(u => u.UserName == username).FirstOrDefault();
                        string otherUserId = otherUserInDb.Id;
                        var currentUserInDb = _context.Users.Where(u => u.Id == currentUserId).FirstOrDefault();

                        if (currentUserInDb == null || otherUserInDb == null)
                        {
                            return Json(new { error = "User not found" });
                        }

                        var friendInDb = _context
                            .Friends
                            .SingleOrDefault(u => (u.User1Id == currentUserId || u.User2Id == currentUserId) && (u.User1Id == otherUserId || u.User2Id == otherUserId));

                        if (friendInDb == null)
                        {
                            Friend friend = new Friend()
                            {
                                User1Id = currentUserId,
                                User2Id = otherUserId,
                                ActingUserId = currentUserId,
                                Status = FriendStatus.Requested
                            };

                            _context.Friends.Add(friend);
                            _context.SaveChanges();
                        }
                        else
                        {
                            friendInDb.ActingUserId = currentUserId;
                            friendInDb.Status = FriendStatus.Requested;

                            _context.Friends.Update(friendInDb);
                            _context.SaveChanges();
                        }

                        NotificationsController.AddNotification(
                            _context, 
                            NotificationType.FriendRequested, 
                            otherUserInDb, 
                            null, 
                            currentUserInDb, 
                            null, 
                            null
                        );

                        transaction.Commit();

                        // Return a null json result as the POST is expecting json
                        return Json(new { success = true });
                    }

                    return Json(new { error = "Unable to add friend" });
                }
                catch (Exception e)
                {
                    return Json(new { error = e.Message });
                }
            }
        }

        [HttpPost]
        public ActionResult AcceptFriend(string username)
        {
            var friendStatus = CheckFriendStatus(username);

            using (var transaction = _context.Database.BeginTransaction())
            {
                try
                {
                    if (friendStatus != FriendStatus.Blocked)
                    {
                        string currentUserId = User.GetUserId();
                        string currentUsername = User.GetUsername();                        
                        var otherUserInDb = _context.Users.Where(u => u.UserName == username).FirstOrDefault();
                        string otherUserId = otherUserInDb.Id;
                        var currentUserInDb = _context.Users.Where(u => u.Id == currentUserId).FirstOrDefault();

                        if (currentUserInDb == null || otherUserInDb == null)
                        {
                            return Json(new { error = "User not found" });
                        }

                        var friendInDb = _context
                            .Friends
                            .SingleOrDefault(u => (u.User1Id == currentUserId || u.User2Id == currentUserId) && (u.User1Id == otherUserId || u.User2Id == otherUserId));

                        if (friendInDb != null)
                        {
                            friendInDb.Status = FriendStatus.Friends;

                            _context.Friends.Update(friendInDb);
                            _context.SaveChanges();
                        }

                        NotificationsController.AddNotification(
                            _context, 
                            NotificationType.FriendAccepted, 
                            otherUserInDb, 
                            null, 
                            currentUserInDb, 
                            null, 
                            null
                        );

                        transaction.Commit();

                        // Return a null json result as the POST is expecting json
                        return Json(new { success = true });
                    }

                    return Json(new { error = "Unable to accept friend" });
                }
                catch (Exception e)
                {
                    return Json(new { error = e.Message });
                }
            }
        }

        [HttpPost]
        public ActionResult DeclineFriend(string username)
        {
            var friendStatus = CheckFriendStatus(username);

            try

TabRepository/Views/Friends/Search.cshtml
@model IEnumerable<TabRepository.ViewModels.FriendViewModel>
@{
    ViewData["Title"] = "Search";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid list-container" style="display: block;">
    <div id="page">
        <div class="row list-row">
            @foreach (var user in Model)
            {
                <div class="col-lg-4" align="center">
                    <div class="card card-profile">
                        <div class="card-header" style="background-image: url('@(user.ImageFilePath == null ? "/images/TabCollab_icon_white_square_512.png" : user.ImageFilePath)');"></div>
                        <div class="card-body text-center">
                            <h3 style="margin-bottom: 1.25rem;">@user.Username</h3>
                            <div>
                                @if (!@user.IsCurrentUser)
                                {
                                    if (@user.Status == FriendStatus.None)
                                    {
                                        <a id="add-friend-button" data-username="@user.Username" class="btn btn-primary" href="@Url.Action("AddFriend", "Friends")">Add Friend</a>
                                    }
                                    else if (@user.Status == FriendStatus.Requested)
                                    {
                                        if (@user.Direction == Direction.To)
                                        {
                                            <a class="btn btn-default pull-left disabled">Request Sent</a>
                                            <a id="cancel-request-button" data-username="@user.Username" class="btn btn-danger pull-right" href="@Url.Action("CancelRequest", "Friends")">Cancel Request</a>
                                        }
                                        else
                                        {
                                            <a id="accept-friend-button" data-username="@user.Username" class="btn btn-info pull-left" href="@Url.Action("AcceptFriend", "Friends")">Accept Friend</a>
                                            <a id="decline-friend-button" data-username="@user.Username" class="btn btn-danger pull-right" href="@Url.Action("DeclineFriend", "Friends")">Decline Friend</a>
                                        }
                                    }
                                    else if (@user.Status == FriendStatus.Friends)
                                    {
                                        <a class="btn btn-primary pull-left">Friends</a>
                                        <a id="remove-friend-button" data-username="@user.Username" class="btn btn-danger pull-right" href="@Url.Action("RemoveFriend", "Friends")">Unfriend</a>
                                    }
                                }
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@section scripts
    {
    <script>
        $(document).ready(function () {
            $('footer').show();

            // Add friend
            $("#page").on("click", "#add-friend-button", function (e, data) {
                e.preventDefault();

                var href = this.href,
                    that = this;
                username = { username: $(that).attr('data-username') };

                $.ajax({
                    url: href,
                    type: 'POST',
                    data: username,
                    dataType: 'json'
                })
                .then(function (response) {
                    if (response.error) {
                        showFailureBootbox("sending friend request", response.error);
                    }
                    else {
                        $(that).html("Request Sent");
                        $(that).toggleClass('btn-primary btn-default disabled pull-left');
                        $(that).parent().append('<a id="cancel-request-button" data-username="' + username.username + '" class="btn btn-danger pull-right" href="/Friends/CancelRequest">Cancel Request</a>');
                    }                        
                })
                .fail(function (error) {
                    showFailureBootbox("sending friend request", error.statusText);
                })
            });

            // Accept friend
            $("#page").on("click", "#accept-friend-button", function (e, data) {
                e.preventDefault();

                var href = this.href,
                    that = this;
                username = { username: $(that).attr('data-username') };

                $.ajax({
                    url: href,
                    type: 'POST',
                    data: username,
                    dataType: 'json'
                })
                .then(function (response) {
                    if (response.error) {
                        showFailureBootbox("accepting friend request", response.error);
                    }
                    else {
                        $(that).html("Friends");
                        $(that).parent().html('<a class="btn btn-primary pull-left">Friends</a><a id="remove-friend-button" data-username="' + username.username + '" class="btn btn-danger pull-right" href="/Friends/RemoveFriend">Unfriend</a>')
                    }                   
                })
                .fail(function (error) {
                    showFailureBootbox("accepting friend request", error.statusText);
                })
            });

            // Remove friend
            $("#page").on("click", "#remove-friend-button", function (e, data) {
                e.preventDefault();

                var href = this.href,
                    that = this;
                username = { username: $(that).attr('data-username') };

                bootbox.confirm("Are you sure you wish to unfriend " + username.username + "?", function (result) {
                    if (result) {
                        $.ajax({
                            url: href,
                            type: 'POST',
                            data: username,
                            dataType: 'json'
                        })
                        .then(function (response) {
                            if (response.error) {
                                showFailureBootbox("removing friend", response.error);
                            }
                            else {
                                $(that).parent().html('<a id="add-friend-button" data-username="' + username.username + '" class="btn btn-primary" href="/Friends/AddFriend">Add Friend</a>');
                            }                            
                        })
                        .fail(function (error) {
                            showFailureBootbox("removing friend", error.statusText);
                        })
                    }
                });
            });

            // Decline friend
            $("#page").on("click", "#decline-friend-button", function (e, data) {
                e.preventDefault();

                var href = this.href,
                    that = this;
                username = { username: $(that).attr('data-username') };

                $.ajax({
                    url: href,
                    type: 'POST',
                    data: username,
                    dataType: 'json'
                })
                .then(function (response) {
                    if (response.error) {
                        showFailureBootbox("declining friend request", response.error);
                    }
                    else {
                        $(that).parent().html('<a id="add-friend-button" data-username="' + username.username + '" class="btn btn-primary" href="/Friends/AddFriend">Add Friend</a>');
                    }                    
                })
                .fail(function (error) {
                    showFailureBootbox("declining friend request", error.statusText);
                })
            });

            // Cancel request
            $("#page").on("click", "#cancel-request-button", function (e, data) {
                e.preventDefault();

                var href = this.href,
                    that = this;
                username = { username: $(that).attr('data-username') };

                $.ajax({
                    url: href,
                    type: 'POST',
                    data: username,
                    dataType: 'json'
                })
                .then(function (response) {
                    if (response.error) {
                        showFailureBootbox("canceling friend request", response.error);
                    }
                    else {
                        $(that).parent().html('<a id="add-friend-button" data-username="' + username.username + '" class="btn btn-primary" href="/Friends/AddFriend">Add Friend</a>');
                    }                    
                })
                .fail(function (error) {
                    showFailureBootbox("canceling friend request", error.statusText);
                })
            });
        });
    </script>
}

TabRepository/Views/Friends/_FriendsList.cshtml
@model IEnumerable<TabRepository.ViewModels.FriendViewModel>

@if (Model.Count() > 0)
{
    <div class="row list-row">
        @foreach (var user in Model)
        {
            <div class="col-lg-4" align="center">
                <div class="card card-profile">
                    <div class="card-header" style="background-image: url('@(user.ImageFilePath == null ? "/images/TabCollab_icon_white_square_512.png" : user.ImageFilePath)');"></div>
                    <div class="card-body text-center">
                        <h3 style="margin-bottom: 1.25rem;">@user.Username</h3>
                        <div>
                            @if (!@user.IsCurrentUser)
                            {
                                if (@user.Status == FriendStatus.None)
                                {
                                    <a id="add-friend-button" data-username="@user.Username" class="btn btn-primary" href="@Url.Action("AddFriend", "Friends")">Add Friend</a>
                                }
                                else if (@user.Status == FriendStatus.Requested)
                                {
                                    if (@user.Direction == Direction.To)
                                    {
                                        <a class="btn btn-default pull-left disabled">Request Sent</a>
                                        <a id="cancel-request-button" data-username="@user.Username" class="btn btn-danger pull-right" href="@Url.Action("CancelRequest", "Friends")">Cancel Request</a>
                                    }
                                    else
                                    {
                                        <a id="accept-friend-button" data-username="@user.Username" class="btn btn-info pull-left" href="@Url.Action("AcceptFriend", "Friends")">Accept Friend</a>
                                        <a id="decline-friend-button" data-username="@user.Username" class="btn btn-danger pull-right" href="@Url.Action("DeclineFriend", "Friends")">Decline Friend</a>
                                    }
                                }
                                else if (@user.Status == FriendStatus.Friends)
                                {
                                    <a class="btn btn-primary pull-left">Friends</a>
                                    <a id="remove-friend-button" data-username="@user.Username" class="btn btn-danger pull-right" href="@Url.Action("RemoveFriend", "Friends")">Unfriend</a>
                                }
                            }
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
}
else
{
    <div class="flex-container-row empty-list">
        <div class="flex-container-col">
            <h2 style="color: grey">You don't have any friends (on TabCollab).</h2>
        </div>
    </div>
}