TabRepository/Models/Album.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TabRepository.Interfaces;

namespace TabRepository.Models
{
    public class Album : IItem
    {
        public int Id { get; set; }

        public string UserId { get; set; }

        public int ProjectId { get; set; }

        public string Description { get; set; }

        public string ImageFileName { get; set; }

        public string ImageFilePath { get; set; }

        [Required]
        [Display(Name = "Album Name")]
        [StringLength(255)]
        public string Name { get; set; }

        public int CurrentVersion { get; set; }

        public int Order { get; set; }

        public DateTime DateCreated { get; set; }

        public DateTime DateModified { get; set; }

        public virtual Project Project { get; set; }

        public virtual ApplicationUser User { get; set; }

        public virtual ICollection<Tab> Tabs { get; set; }
    }
}

TabRepository/Controllers/AlbumsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TabRepository.Data;
using TabRepository.Helpers;
using TabRepository.Models;
using TabRepository.ViewModels;

namespace TabRepository.Controllers
{
    [Authorize]
    public class AlbumsController : Controller
    {
        private ApplicationDbContext _context;
        private FileUploader _fileUploader;
        private readonly IHostingEnvironment _appEnvironment;
        private UserAuthenticator _userAuthenticator;

        public AlbumsController(ApplicationDbContext context, IHostingEnvironment appEnvironment, UserAuthenticator userAuthenticator)
        {
            _context = context;
            _appEnvironment = appEnvironment;
            _fileUploader = new FileUploader(context, appEnvironment);
            _userAuthenticator = userAuthenticator;
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        public ActionResult New(int projectId)
        {
            string currentUserId = User.GetUserId();

            // Verify current user has access to this project
            var projectInDb = (Project)_userAuthenticator.CheckUserCreateAccess(Item.Project, projectId, currentUserId);

            if (projectInDb == null)
                return Json(new { error = "Project not found" });

            var viewModel = new AlbumFormViewModel()
            {
                ProjectId = projectInDb.Id,
                ProjectName = projectInDb.Name
            };

            return View("AlbumForm", viewModel);
        }


        // POST: Albums
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Save(AlbumFormViewModel viewModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string currentUserId = User.GetUserId();
                    string currentUsername = User.GetUsername();
                    var userInDb = _context.Users.Where(u => u.Id == currentUserId).FirstOrDefault();

                    if (userInDb == null)
                    {
                        return Json(new { error = "User not found" });
                    }

                    // Verify current user has access to this project
                    var projectInDb = (Project)_userAuthenticator.CheckUserCreateAccess(Item.Project, viewModel.ProjectId, currentUserId);

                    if (projectInDb == null)
                    {
                        return Json(new { error = "Project not found" });
                    }

                    if (viewModel.Id == 0)  // We are creating a new album
                    {
                        using (var transaction = _context.Database.BeginTransaction())
                        {
                            Album album = new Album()
                            {
                                UserId = projectInDb.UserId,
                                Project = projectInDb,
                                Name = viewModel.Name,
                                Description = viewModel.Description,
                                DateCreated = DateTime.Now,
                                DateModified = DateTime.Now
                            };

                            if (viewModel.CroppedImage != null)
                            {
                                // Limit file size to 1 MB
                                if (viewModel.CroppedImage.Length > 1000000)
                                {
                                    return Json(new { error = "Image size limit is 1 MB" });
                                }

                                Helpers.File file = await _fileUploader.UploadFileToFileSystem(viewModel.CroppedImage, projectInDb.UserId, "Album" + album.Id.ToString());

                                album.ImageFilePath = file.Path;
                                album.ImageFileName = file.Name;
                            }

                            _context.Albums.Add(album);
                            _context.SaveChanges();

                            NotificationsController.AddNotification(
                                _context, 
                                NotificationType.AlbumAdded, 
                                null, 
                                album.ProjectId, 
                                userInDb, 
                                album.Name, 
                                album.Project.Name
                            );

                            transaction.Commit();

                            return Json(new { name = album.Name, id = album.Id, imageFilePath = album.ImageFilePath == null ? "/images/TabCollab_icon_white_square_512.png" : album.ImageFilePath });
                        }
                    }
                    else // We're updating an album
                    {
                        var albumInDb = (Album)_userAuthenticator.CheckUserEditAccess(Item.Album, viewModel.Id, currentUserId);

                        // If current user does not have access to project or project does not exist
                        if (albumInDb == null)
                        {
                            return Json(new { error = "Album not found" });
                        }

                        albumInDb.Name = viewModel.Name;
                        albumInDb.Description = viewModel.Description;
                        albumInDb.DateModified = DateTime.Now;

                        if (viewModel.CroppedImage != null)
                        {
                            // Limit file size to 1 MB
                            if (viewModel.CroppedImage.Length > 1000000)
                            {
                                return Json(new { error = "Image size limit is 1 MB" });
                            }

                            Helpers.File file = await _fileUploader.UploadFileToFileSystem(viewModel.CroppedImage, User.GetUserId(), "Album" + albumInDb.Id.ToString());

                            albumInDb.ImageFilePath = file.Path;
                            albumInDb.ImageFileName = file.Name;
                        }

                        _context.Albums.Update(albumInDb);
                        _context.SaveChanges();

                        return Json(new { name = albumInDb.Name, id = albumInDb.Id, imageFilePath = albumInDb.ImageFilePath == null ? "/images/TabCollab_icon_white_square_512.png" : albumInDb.ImageFilePath });
                    }
                }

                // If we got here there were errors in the modelstate                
                var modelErrors = ModelState.Values.SelectMany(v => v.Errors.Select(b => b.ErrorMessage)).ToList();

                return Json(new { error = string.Join("<br />", modelErrors) });
            }
            catch (Exception e)
            {
                return Json(new { error = e.Message });
            }        
        }

        [HttpDelete]
        public ActionResult Delete(int id)
        {
            try
            {
                using (var transaction = _context.Database.BeginTransaction())
                {
                    string currentUserId = User.GetUserId();
                    string currentUsername = User.GetUsername();
                    var userInDb = _context.Users.Where(u => u.Id == currentUserId).FirstOrDefault();

                    if (userInDb == null)
                    {
                        return Json(new { error = "User not found" });
                    }

                    var albumInDb = (Album)_userAuthenticator.CheckUserDeleteAccess(Item.Album, id, currentUserId);

                    // If current user does not have access to project or project does not exist
                    if (albumInDb == null)
                    {
                        return Json(new { error = "Album not found" });
                    }                        

                    _context.Albums.Remove(albumInDb);
                    _context.SaveChanges();

                    NotificationsController.AddNotification(
                        _context, 
                        NotificationType.AlbumDeleted, 
                        null, 
                        albumInDb.ProjectId, 
                        userInDb, 
                        albumInDb.Name, 
                        albumInDb.Project.Name
                    );

                    transaction.Commit();

                    return Json(new { success = true });
                }
            }
            catch (Exception e)
            {
                return Json(new { error = e.Message });
            }
        }

        // GET: Albums
        public ViewResult Index()
        {
            return View();
        }

        public ApplicationUser GetCurrentUser()
        {
            string currentUserId = User.GetUserId();

            return _context.Users.FirstOrDefault(u => u.Id == currentUserId);
        }

        // GET: Album form
        // Two scenarios for this method:
        // projectId == 0 and albumId != 0 -> editing album
        // projectId != 0 and albumId == 0 -> creating new album
        [HttpGet]
        public ActionResult GetAlbumFormPartialView(int projectId, int albumId)
        {
           try
            {
                string currentUserId = User.GetUserId();
                var viewModel = new AlbumFormViewModel();

                // New album
                if (albumId == 0)
                {
                    // Verify current user has access to this project
                    var projectInDb = (Project)_userAuthenticator.CheckUserCreateAccess(Item.Project, projectId, currentUserId);

TabRepository/Views/Albums/AlbumForm.cshtml
@model TabRepository.ViewModels.AlbumFormViewModel
@{
    ViewBag.Title = "AlbumForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>New Album</h2>

<p>PROJECT NAME: @Model.ProjectName</p>

<form id="project-form" asp-controller="Albums" asp-action="Save" data-ajax="true" data-ajax-method="POST">
        @Html.LabelFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        <span asp-validation-for="Name" style="color: red"></span>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Description)
        @Html.TextBoxFor(m => m.Description, new { @class = "form-control" })
        <span asp-validation-for="Description" style="color: red"></span>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Image)
        @Html.TextBoxFor(m => m.Image, new { type = "file", @class = "btn btn-default" })
        <span asp-validation-for="Image" style="color: red"></span>
    </div>
    @Html.HiddenFor(m => m.ProjectId)
    @Html.AntiForgeryToken()
    <button type="submit" class="btn btn-primary"> Save</button>
</form>

TabRepository/Views/Albums/Index.cshtml
@{
    ViewBag.Title = "Albums";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid list-container" style="display: flex;">
    <div class="add-button-container">
        <a id="new-album-button" class="white-icon add-button" href="@Url.Action("GetProjectSelectionPartialView", "Projects")"><i data-toggle="tooltip" title="Add New Album" class="fa fa-plus fa-3x"></i></a>
    </div>
    <div id="album-container">
        <div id="album-list-wrapper"></div>

        <div id='album-form-modal' class='modal fade'>
            <div id='album-form-container'>
            </div>
        </div>
    </div>
    <div id="list-loader-wrapper" class="flex-container-row">
        <div class="flex-container-col">
            <div class="list-loader"></div>
        </div>
    </div>
    <div class="add-button-container" style="visibility: hidden">
        <i class="fa fa-plus fa-3x"></i>
    </div>
</div>

@section scripts
    {
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

    <script>
$(document).ready(function () {
    repopulateAlbumList()
        .then(function (result) {
            $('#list-loader-wrapper').remove();           
            $('hr').show();
            $('footer').show();
        })
        .catch(function (error) {
            bootbox.alert("Unable to load albums. Error: " + error.statusText);
        });

    // Only show tooltips on non-touchscreens
    if (!('ontouchstart' in window)) {
        $('[data-toggle="tooltip"]').tooltip({ trigger: "hover" });
    }

    // Deleting an album
    $(document).on("click", "#delete-album-button", function (e, data) {
        e.preventDefault();

        var href = this.href,
            that = this;

        bootbox.prompt("Confirm Delete", function (result) {
            if (result == $(that).attr("data-name")) {
                $.ajax({
                    type: 'DELETE',
                    dataType: 'json',
                    traditional: 'true',
                    url: href
                })
                .then(function (response) {
                    if (response.error) {
                        showFailureBootbox("deleting album", response.error);
                    }
                    else {
                        repopulateAlbumList();
                    }
                })
                .fail(function (error) {
                });
            }
            else if (result != null) {
                bootbox.alert("Name did not match.");
            }
        });

        // CSS change to make the title display properly and add prompt text
        $('.modal-header').css('display', 'unset')
        $('.bootbox-body').prepend("<p>Are you sure you wish to delete this album? This cannot be undone.<br />Confirm by typing the albums's name below:</p>")
    });

    // Show modal for new project
    $(document).on("click", "#new-album-button", function (e, data) {
        e.preventDefault();

        var href = this.href;

        $.ajax({
            url: href,
            type: 'GET',
        })
        .then(function (response) {
            if (response.error) {
                showFailureBootbox("showing album form", response.error);
            }
            else {
                $('#album-form-container').html(response);

                // Client side validation for dynamic modal injection
                $.validator.unobtrusive.parse($("#album-form"));

                currentModal = $('#album-form-modal');
                currentModal.modal('show');
            }
        })
        .fail(function (error) {
            showFailureBootbox("showing album form", error.statusText);
        })
    });

    // Show modal for edit album
    $(document).on("click", "#edit-album-button", function (e, data) {
        e.preventDefault();

        var href = this.href + "?projectId=" + $(this).attr("data-project-id") + "&albumId=" + $(this).attr("data-album-id");

        $.ajax({
            url: href,
            type: 'GET',
        })
        .then(function (response) {
            if (response.error) {
                showFailureBootbox("showing album form", response.error);
            }
            else {
                $('#album-form-container').html(response);
                // Client side validation for dynamic modal injection
                $.validator.unobtrusive.parse($("#album-form"));

                imageUpload();

                currentModal = $('#album-form-modal');
                currentModal.modal('show');
            }
        })
        .fail(function (error) {
            showFailureBootbox("showing album form", error.statusText);
        })
    });

    $(document).on("click", ".show-buttons-icon", function (e, data) {
        // Only show tooltips on non-touchscreens
        if (!('ontouchstart' in window)) {
            $('[data-toggle="tooltip"]').tooltip({ trigger: "hover" });
        }

        var parent = $(this).parent();

        $(parent).hide();
        $(parent).siblings('.item-container').show(200);
        // Wait until the expansion animation is complete to show the buttons
        setTimeout(function () {
            $(parent).siblings('.item-container').children().css("visibility", "visible");
        }, 200)
        $(parent).siblings('.hide-items-icon-container').show();
    });

    $(document).on("click", ".hide-buttons-icon", function (e, data) {

        var parent = $(this).parent();

        $(parent).hide();
        $(parent).siblings('.item-container').children().css("visibility", "hidden");
        $(parent).siblings('.item-container').hide(200);
        $(parent).siblings('.show-items-icon-container').show();
    });

    $(document).on("keypress", ".show-buttons-icon, .hide-buttons-icon", function (e, data) {
        var key = e.which;
        if (key === 13)  // the enter key code
        {
            $(this).click();
            return false;
        }
    });

    $(document).on("click", ".project-selection-panel", function (e, data) {
        e.preventDefault();

        var that = this;

        // Give modal time to close
        setTimeout(function () {
            var href = "@Url.Action("GetAlbumFormPartialView", "Albums")" + "/?projectId=" + $(that).attr("data-project-id");

            $.ajax({
                url: href,
                type: 'GET',
            })
            .then(function (response) {
                if (response.error) {
                    showFailureBootbox("showing album form", response.error);
                }
                else {
                    $('#album-form-container').html(response);
                    // Client side validation for dynamic modal injection
                    $.validator.unobtrusive.parse($("#album-form"));

                    imageUpload();

                    currentModal = $('#album-form-modal');
                    currentModal.modal('show');
                }
            })
            .fail(function (error) {
                showFailureBootbox("showing album form", error.statusText);
            })
        }, 500)
    });

    $("#album-container").on("submit", function (e, data) {
        e.preventDefault();

        var $deferred = $.Deferred();

        // Don't submit form if the image is too large
        if ($('#Image')[0].files.length) {
            if ($('#Image')[0].files[0].size > 1000000) {
                return
            }
            $('#image-upload').croppie('result', {
                type: 'blob',
                size: 'original',
                format: 'jpeg'
            }).then(function (blob) {
                $deferred.resolve(blob);
            });
        }
        else {
            $deferred.resolve();
        }

        $deferred.then(function (blob) {
            var form = e.target;
            var formData = new FormData(form);

            if (blob) {
                formData.append('CroppedImage', blob, 'image.jpeg');
            }

            // Show spinner on save button
            $('.button-save').html('<div class="loader"></div>');
            $('.button-save').addClass('disabled');
            $('.validation-error').html('');

            $.ajax({
                url: form.action,
                type: 'POST',
                data: formData,
                cache: false,
                contentType: false,
                processData: false
            })
            .then(function (response) {
                if (response.error) {
                    enableSubmitButton();
                    if (response.error.toLowerCase().includes('file')) {
                        $('#image-error').html(response.error);
                    }
                    else {
                        showFailureBootbox("saving", response.error);
                    }
                }
                else {
                    currentModal.modal('hide');
                    // Call GetAlbumListPartialView to repopulate the project list
                    repopulateAlbumList();
                }
            })
            .fail(function (error) {
                showFailureBootbox("saving album", error.statusText);
                enableSubmitButton();
            })
        });
    });

    function repopulateAlbumList() {
        return new Promise((resolve, reject) => {
            var url = '@Url.Action("GetAlbumListPartialView", "Albums", null)';

            $.ajax({
                url: url,
                type: 'GET',
            })
            .then(function (response) {
                if (response.error) {
                    showFailureBootbox("retrieving album list", response.error);
                }
                else {
                    // If we get back empty-list, empty out any existing projects and set CSS for proper display
                    if (response.includes('empty-list')) {
                        $('#album-list-wrapper').empty();
                        $('#album-container').after(response);
                        $('.list-container').css('flex-direction', 'row');
                    }
                    else {
                        $('.empty-list').remove();
                        $('#album-list-wrapper').empty().append(response);
                        $('.list-container').css('flex-direction', 'column');
                    }
                }

                resolve();
            })
            .fail(function (error) {
                showFailureBootbox("retrieving album list", error.statusText.error);
                reject();
            })
        })
    }

    function enableSubmitButton() {
        $('.button-save').html('Save');
        $('.button-save').removeClass('disabled');
    }
});
    </script>
}

TabRepository/Views/Albums/_AlbumForm.cshtml
@model TabRepository.ViewModels.AlbumFormViewModel

<div class="modal-dialog text-left">
    <!-- Modal content-->
    <div class="modal-content">
        <div class="modal-header">
            @if (String.IsNullOrEmpty(Model.Name))
            {
                <h4 class="modal-title">New Album for @Model.ProjectName</h4>
            }
            else
            {
                <h4 class="modal-title">Edit @Model.Name</h4>
            }
            <button type="button" class="close modal-close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <form id="album-form" asp-controller="Albums" asp-action="Save" data-ajax="true" data-ajax-method="POST">
                <div class="form-group">
                    @Html.LabelFor(m => m.Name)
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control form-input" })
                    <div class="form-label">
                        <span asp-validation-for="Name" style="color: red"></span>
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Description)
                    @Html.TextAreaFor(m => m.Description, new { @class = "form-control form-input" })
                    <div class="form-label">
                        <span asp-validation-for="Description" style="color: red"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="form-label image-upload">
                        @Html.LabelFor(m => m.Image, "Album Image")
                        <div id="image-upload-container" style="display: none;">
                            <div id="image-upload"></div>
                        </div>
                    </div>
                    @Html.TextBoxFor(m => m.Image, new { type = "file", @class = "btn btn-default form-input file-input" })
                    <div class="form-label">
                        <span id="image-error" class="validation-error" style="color: red"></span>
                    </div>
                </div>
                @Html.HiddenFor(m => m.ProjectId)
                @Html.HiddenFor(m => m.Id)
                @Html.AntiForgeryToken()
            </form>
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary button-save" form="album-form">Save</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
    </div>
</div>

TabRepository/Views/Albums/_AlbumList.cshtml
@model IEnumerable<TabRepository.ViewModels.AlbumIndexViewModel>

@if (Model.Count() > 0)
{
    <div class="row list-row">
        @foreach (var album in Model)
        {
            <div class="col-lg-4" align="center">
                <div class="card card-profile">
                    <div class="card-header" style="background-image: url('@(album.ImageFilePath == null ? "/images/TabCollab_icon_white_square_512.png" : album.ImageFilePath)');"></div>
                    <div class="card-body text-center">
                        <h3>@album.Name</h3>
                        <p class="m-b">Project: @album.ProjectName<br />Owner: @album.Owner</p>
                        @if (album.IsOwner)
                        {
                            <div class="show-items-icon-container">
                                <i class="fa fa-lg fa-chevron-down show-buttons-icon" tabindex="0"></i>
                            </div>
                            <div class="item-container">
                                <a id="edit-album-button" style="visibility: hidden;" data-toggle="tooltip" title="Edit Album" class="pull-left list-icon white-icon" data-project-id="@album.ProjectId" data-album-id="@album.Id" href="@Url.Action("GetAlbumFormPartialView", "Albums")"><i class="fa fa-pencil fa-lg" /></a>
                                <a id="delete-album-button" style="visibility: hidden;" data-toggle="tooltip" title="Delete Album" class="pull-right list-icon white-icon" data-name="@album.Name" href="@Url.Action("Delete", "Albums", new { id = album.Id })"><i class="fa fa-times fa-lg" /></a>
                            </div>
                            <div class="hide-items-icon-container">
                                <i class="fa fa-lg fa-chevron-up hide-buttons-icon" tabindex="0"></i>
                            </div>
                        }
                    </div>
                </div>
            </div>
        }
    </div>
}
else
{
    <div class="flex-container-row empty-list">
        <div class="flex-container-col">
            <h2 style="color: grey">You don't have any albums.</h2>
        </div>
    </div>
}

TabRepository/Views/Albums/_AlbumSelection.cshtml
@model IEnumerable<TabRepository.ViewModels.AlbumIndexViewModel>

<div class="modal-dialog selection-modal" align="center">
    <!-- Modal content-->
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Select Album</h4>
            <button type="button" class="close modal-close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            @if (Model.Count() == 0)
            {
                <h4 style="text-align: center;">There are no albums for this project.</h4>
            }
            @foreach (var album in Model)
            {
                <div class="row">
                    <div class="card card-profile selection-panel album-selection-panel" data-album-id="@album.Id" data-dismiss="modal">
                        <div class="card-header" style="background-image: url('@(album.ImageFilePath == null ? "/images/TabCollab_icon_white_square_512.png" : album.ImageFilePath)');"></div>
                        <div class="card-body">
                            <h3 style="text-align: center;">@album.Name</h3>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>